version: 2

sources:
  - name: del2
    database: cse_sandbox_database
    schema: dbt_sbeard
    tables:
      - name: customers
      - name: '"Customers_Two"'


  - name: del
    database: cse_sandbox_database
    schema: dbt_sbeard
    quoting:
      identifier: true
    tables:
      - name: Temp_Delete_Ollie_rename_test_3
        columns:
          - name: ColumnOne
            quote: true
          - name: ColumnTwo
            quote: true
          - name: product_id
          - name: salesid
            quote: true
      - name: Customers_Two