version: 2

sources:
  - name: del
    database: cse_sandbox_database
    schema: dbt_sbeard
    quoting:
      identifier: true
    tables:
      - name: Temp_Delete_Ollie_rename_test
        columns:
          - name: column_one
            quote: true
            data_tests:
              - not_null
          - name: column_two
            quote: true
          - name: product_id
            quote: true
          - name: sales_id
            quote: true